project:
  type: website
  output-dir: docs
  render:
    - index.qmd
    - publications.qmd
    - events.qmd
    - code.qmd
    
website:
  title: ""
  search: true
  navbar:
    left:
      - href: index.qmd
        text: About SAVVY
      - href: publications.qmd
        text: Publications
      - href: events.qmd
        text: Events and talks
      - href: code.qmd
        text: Code

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

