---
title: "SAVVY: estimation of AE probabilities"
author: "Regina Stegherr and Kaspar Rufibach"
output: 
  rmarkdown::html_document:
    highlight: pygments
    number_sections: no
    self_contained: yes
    toc: yes
    toc_depth: 3
    toc_float: yes
    code_download: true
bibliography: stat.bib
---

# Background

The assessment of safety is an important aspect of the evaluation of new therapies in clinical trials, with analyses of adverse events being an essential part of this. Standard methods for the analysis of adverse events such as the incidence proportion, i.e. the number of patients with a specific adverse event out of all patients in the treatment groups, do not account for both varying follow-up times and competing risks. Alternative approaches such as the Aalen-Johansen estimator of the cumulative incidence function have been suggested. Theoretical arguments and numerical evaluations support the application of these more advanced methodology, but as yet there is to our knowledge only insufficient empirical evidence whether these methods would lead to different conclusions in safety evaluations. The Survival analysis for AdVerse events with VarYing follow-up times (SAVVY) project strives to close this gap in evidence by conducting a meta-analytical study to assess the impact of the methodology on the conclusion of the safety assessment empirically. Three papers are currently under review summarizing the rationale and results of the project:

-   @stegherr_20_sap: Statistical analysis plan, presenting the rationale and statistical concept of the empirical study conducted as part of the SAVVY project. The statistical methods are presented in unified notation and examples of their implementation in R and SAS are provided. [arxiv](https://arxiv.org/abs/1912.00263) \| [publication](https://doi.org/10.1002/bimj.201900347)
-   @stegherr_20_1sample: 1-sample case, compares estimators of AE risk in one treatment arm. [arxiv](https://arxiv.org/abs/2008.07883) \| [publication](https://doi.org/10.1186/s13063-021-05354-x)
-   @rufibach_20_2sample: 2-sample case, compares relative risk estimators comparing two treatment arms based on (1) AE probabilities and (2) hazards. [arxiv](https://arxiv.org/abs/2008.07881) \| [publication](https://doi.org/10.1080/19466315.2022.2144944)

# Purpose of this document

This R markdown file provides easy accessible code to compute all the estimators for AE probabilities that are compared to each other in these papers. The github repository where this document is hosted is available [here](https://github.com/numbersman77/savvy).

# SAS code

The original SAS macros that were used by each sponsor to generate the summary data for the meta-analysis is available as supplement to @stegherr_20_sap, see [here](https://doi.org/10.1002/bimj.201900347), or [direct download link](https://onlinelibrary.wiley.com/action/downloadSupplement?doi=10.1002%2Fbimj.201900347&file=bimj2199-sup-0001-SuppMat.zip) for zip-file.

# R code

All code for SAVVY has been implemented in the [savvyr R package]() (also on [github](https://openpharma.github.io/savvyr/)). See the [vignette](https://cran.r-project.org/web/packages/savvyr/vignettes/introduction.html) for an introduction on its use. 

# References
